rule all:
    input:
        "processed_output.txt"

rule convert_to_uppercase:
    input:
        "input.txt"
    output:
        "processed_output.txt"
    shell:
        "echo 'Processing...' && tr '[:lower:]' '[:upper:]' < {input} > {output} && echo 'Done!'"